client_params:
  num_clients: 1

  train_test_split: # train test split config
    train: 0.8
    test: 0.2

  dataset: # dataset hyperparameters and configs
    preprocessor: default
    distribution:
      distributor: non_iid_dist_extreme
      iid: True # if IID is true, it will skip the clients distribution ration in the next variable
      clients: # example client dataset distribution for 3 clients
        - 1.0

  model_params: # model and training files and configs
    model_file: simple_cnn_cifar
    parameter_mixer: default
    training_loop_file: cel_simple
    test_file: multi_cel_simple

  train_params: # training parameters
    learning_rate: 0.1
    batch_size: 128
    local_epochs: 1

    extra_params:
      fed_prox:
        mu: 0.3
      lr_decay: 1

server_params:
  aggregator: fed_avg
  model_file: simple_cnn_cifar
  test_file: multi_cel_simple

  train_params: # training parameters
    rounds: 20

    extra_params: # extra training parameters
      fed_avg_momentum: 0.1

dataset_params:
  prep: cifar_def
