client_params:
  num_clients: 10

  train_test_split: # train test split config
    train: 0.8
    test: 0.2

  dataset: # dataset hyperparameters and configs
    preprocessor: default
    distribution:
      distributor: diritchlet_dist
      extra_params:
        diritchlet_alpha: 0.5

  model_params: # model and training files and configs
    model_file: &model_file 10c_mobilenet
    parameter_mixer: default
    training_loop_file: fed_prox_loop
    test_file: &test_file multi_cel_simple

  train_params: # training parameters
    learning_rate: 0.0001
    batch_size: 32
    local_epochs: 5

    extra_params:
      fed_prox:
        mu: 0.01
      lr_decay: 1

server_params:
  aggregator: fed_avg
  model_file: *model_file
  test_file: *test_file

  train_params: # training parameters
    rounds: 200

    extra_params: # extra training parameters
      fed_avg_momentum: 0.9

dataset_params:
  prep: cifar_def
