client_params:
  num_clients: 3

  train_test_split: # train test split config
    train: 0.8
    test: 0.2

  dataset: # dataset hyperparameters and configs
    preprocessor: default
    distribution:
      distributor: random_dist
      iid: True # if IID is true, it will skip the clients distribution ration in the next variable
      clients: # example client dataset distribution for 3 clients
        - 0.9
        - 0.099
        - 0.001
  
  model_params: # model and training files and configs
    model_file: simple_nn
    parameter_mixer: default
    training_loop_file: simple_loop
    test_file: simple_test


  train_params: # training parameters
    learning_rate: 0.01
    batch_size: 50
    local_epochs: 5
    
    extra_params:
      prox_mu: 0.3
      lr_decay: 1

  

server_params:
  aggregator: fed_avg

  train_params: # training parameters
    rounds: 3

    extra_params: # extra training parameters
      fed_avg_momentum: 0.1
    

dataset_params:
  prep: mnist_def

