client_params:
  num_clients: 1

  train_test_split: # train test split config
    train: 0.8
    test: 0.2

  dataset: # dataset hyperparameters and configs
    preprocessor: default.py
    distribution:
      distributor: random_dist.py
      iid: True # if IID is true, it will skip the clients distribution ration in the next variable
      clients: # example client dataset distribution for 3 clients
        - 0.5
        - 0.3
        - 0.2
  
  model_params: # model and training files and configs
    model_file: simple_nn.py
    parameter_mixer: default.py
    training_loop_file: simple_loop.py
    test_file: simple_test.py


  train_params: # training parameters
    learning_rate: 0.001
    batch_size: 50
    local_epochs: 5
    
    extra_params:
      prox_mu: 0.3
      lr_decay: 1

  

server_params:
  aggregator: fed_avg.py

  train_params: # training parameters
    rounds: 10

    extra_params: # extra training parameters
      fed_avg_momentum: 0.1
    

dataset_params:
  prep: mnist_def.py

