client_params:
  num_clients: 4

  train_test_split: # train test split config
    train: 0.8
    test: 0.2

  dataset: # dataset hyperparameters and configs
    preprocessor: default
    distribution:
      distributor: diritchlet_dist
      clients: # example client dataset distribution for 3 clients
        - 0.25
        - 0.25
        - 0.25
        - 0.25
      extra_params:
        diritchlet_alpha: 0.5

  model_params: # model and training files and configs
    model_file: &model_file simple_mnist
    parameter_mixer: default
    training_loop_file: cel_simple
    test_file: &test_file multi_cel_simple

  train_params: # training parameters
    learning_rate: 0.01
    batch_size: 32
    local_epochs: 5

    extra_params:
      fed_prox:
        mu: 0.1
      lr_decay: 1

server_params:
  aggregator: fed_avg_m
  model_file: *model_file
  test_file: *test_file

  train_params: # training parameters
    rounds: 20

    extra_params: # extra training parameters
      fed_avg_momentum: 0.1

dataset_params:
  prep: mnist_def
